### ISSUE TITLE
Ability to setup local ghost instance

### ISSUE THREAD

**Issue by afs2015** [kallisto/indivisiblesomerville#12]
A user should be able to set up a local version of our ghost stack and have documentation to guide them through it.

**Comment by vyedin** [comment]
I've set danielle up with one so she can play with it for design. This is what I had her follow:

https://guides.co/g/getting-started-with-ghost/9375

**Comment by bhardin** [comment]
This site is down now. Is there a static version of it somewhere?

**Comment by vyedin** [comment]
It seems to be working for me...
