### ISSUE TITLE
Imagery for Website

### ISSUE THREAD

**Issue by afs2015** [kallisto/indivisiblesomerville#9]
If we have any photographs of our group in action that people are okay with us posting on a public website I think they would be great assets for certain pages such as the Join and About pages.

**Comment by vyedin** [comment]
yeah, we have some. They're not super high-quality, but we do have photographers that could make good visuals.

**Comment by afs2015** [comment]
Here's a good list of pages to start with:

[ ] - Join
[ ] - Donate
[ ] - Labs
[ ] - Partnerships
[ ] - Contact

**Comment by vyedin** [comment]
Done in V2
